# What is numpy
Numpy is the fundamental package for scientific computing in python. It is a python library that provides a multidemensional array objects, various derived objects ( such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manupulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statics operations, random simulation and much more.

At the core of the Numpy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.

# Why use numpy when we have list?
Numpy is written in C and wrapped in such a way that it is used in python, Numpy is very fast meanwhile List and other are very slow when dealing with large amount of data.

# Numpy Arrays Vs Python Sequences
- Numpy Arrays have a fixed size at creation, unlike python lists (which can grow dynamically). Changing the size of an ndarrry will create a new array and delete the original.
- The elemenst in Numpy array are all required to be the same data type, and thus will be the same size in memory.
- Numpy arrays facilitate advance mathematical and other types of operations on large number of data. Typically, such operations are executed more efficiently and with less code then is possible using Python's built-in sequences
- A growing plethora of scientific and mathematical Python-based package are using Numpy arrays

In [7]:
# np.array
import numpy as np

a= np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [10]:
# 2D and 3D
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.shape)
print(c)

(2, 3)
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
# dtype
d=np.array([0,1,2,3], dtype=bool)
print(d)
print(d.dtype)

[False  True  True  True]
bool


In [15]:
# np.arrange
e=np.arange(10)
print(e)
np.arange(1,10,2)

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [19]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])