In [2]:
import numpy as np

In [3]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr/arr

/tmp/ipykernel_4972/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.log(arr)

/tmp/ipykernel_4972/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [9]:
arr.sum()

45

In [10]:
arr.mean()

4.5

In [11]:
arr.var()

8.25

In [12]:
arr.std()

2.8722813232690143

In [15]:
arr2d=np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
arr2d.sum()

300

In [22]:
arr2d.sum(axis=0) 

array([50, 55, 60, 65, 70])

In [20]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])