In [1]:
import numpy as np

In [2]:
mylist=[1,2,3,4]


In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3, 4])

In [5]:
myarr=np.array(mylist)
myarr

array([1, 2, 3, 4])

In [6]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,15,3)

array([ 0. ,  7.5, 15. ])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(1)

array([0.98170709])

In [33]:
np.random.rand(3,5)

array([[0.69482842, 0.47274453, 0.56829214, 0.19443155, 0.35375916],
       [0.51218823, 0.71648491, 0.13234429, 0.22085647, 0.4630659 ],
       [0.76714288, 0.19799357, 0.50871121, 0.49491249, 0.05889474]])

In [36]:
np.random.randn(2,4)

array([[-1.19757851, -0.59613815,  0.16772288, -1.41891404],
       [-0.80414392, -0.28571391, -1.97213446, -0.52451582]])

In [39]:
np.random.randint(0,101,(4,5))

array([[13, 61, 61, 48, 66],
       [96, 60,  1, 52, 43],
       [23, 12, 92, 20, 86],
       [46, 29, 12, 74, 56]])

In [41]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
ranarr=np.random.randint(0,101,10)

In [46]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [47]:
ranarr.max()

99

In [49]:
ranarr.argmax()

5

In [51]:
ranarr.dtype

dtype('int64')